# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/mojdigitalstudio/prepare-a-case
  tag: latest
  pullPolicy: Always
  port: 3000

ingress:
  enabled: true
  enable_whitelist: true
  host: prepare-a-case-preprod.apps.live-1.cloud-platform.service.justice.gov.uk
  cert_secret: prepare-a-case-cert
  path: /

env:
  COURT_CASE_SERVICE_URL: https://court-case-service-preprod.apps.live-1.cloud-platform.service.justice.gov.uk
  CASES_PER_PAGE: 20
  NOMIS_AUTH_URL: https://gateway.preprod.nomis-api.service.hmpps.dsd.io/auth

whitelist:
  office: "217.33.148.210/32"
  health-kick: "35.177.252.195/32"
  mojvpn: "81.134.202.29/32"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"
  # @FIXME: settings for Pen Test (PIC-589), remove once completed
  pen-test-1: "31.221.110.80/29"
  pen-test-2: "195.95.131.0/24"
  pen-test-3: "5.148.69.20"
  pen-test-4: "5.148.32.192/26"
  pen-test-5: "193.164.115.0/24"
  pen-test-6: "203.63.205.64/28"
  pen-test-7: "5.148.32.229/32"
  pen-test-8: "119.73.144.40/32"
  pen-test-9: "154.51.128.247"
